/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ecomp.uefs.cliente;

import static br.ecomp.uefs.cliente.ClienteServidores.entradaSV;
import static br.ecomp.uefs.cliente.ClienteServidores.enviarSV;
import static br.ecomp.uefs.cliente.ClienteServidores.receba;
import static br.ecomp.uefs.cliente.ClienteThread.ipReal;
import static br.ecomp.uefs.cliente.ClienteThread.portaRal;
import java.io.IOException;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author wstro
 */
public class Cadastrar extends javax.swing.JFrame {

    /**
     * Creates new form Cadastrar
     */
   
    public Cadastrar() {
        initComponents();
        
    }
    
    
    
    public void iniciar(){
        jLabel1.setVisible(true);
        jLabel2.setVisible(true);
        jLabel3.setVisible(true);
        emailCadastro.setVisible(true);
        SenhaCadastro.setVisible(true);
        LoginCadastro.setVisible(true);
        CancelarCadastro.setVisible(true);
        OKCadastrar.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OKCadastrar = new javax.swing.JButton();
        CancelarCadastro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SenhaCadastro = new javax.swing.JTextField();
        emailCadastro = new javax.swing.JTextField();
        LoginCadastro = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        OKCadastrar.setText("OK");
        OKCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKCadastrarActionPerformed(evt);
            }
        });

        CancelarCadastro.setText("Cancelar");
        CancelarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarCadastroActionPerformed(evt);
            }
        });

        jLabel1.setText("Senha");

        jLabel2.setText("Login");

        jLabel3.setText("Email");

        LoginCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginCadastroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(OKCadastrar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LoginCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelarCadastro)
                    .addComponent(SenhaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LoginCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SenhaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(emailCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OKCadastrar)
                    .addComponent(CancelarCadastro))
                .addGap(89, 89, 89))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarCadastroActionPerformed
        try {
            // TODO add your handling code here:
          Cliente a= new Cliente();
          a.show();
          a.voltar();
          this.setVisible(false);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Cadastrar.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Cadastrar.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_CancelarCadastroActionPerformed

    private void LoginCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginCadastroActionPerformed

    private void OKCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKCadastrarActionPerformed
        // TODO add your handling code here:
   /*
        nessa Action irá enviar as informaççoes cadastradas pelo usuario pelo cliente
        nenhum campo deve ser nulo 
        */
        try {
            
           String login= LoginCadastro.getText();
               String senha=SenhaCadastro.getText();
              String email=emailCadastro.getText();
              
              if(!login.equals("")&& !senha.equals("") &!email.equals("")){
              Cadastrar a= new Cadastrar();
              Cliente ci = new Cliente();
               

              
            enviarSV.writeUTF("cadastro");
             enviarSV.writeUTF(LoginCadastro.getText());
               enviarSV.writeUTF(SenhaCadastro.getText());
               enviarSV.writeUTF(emailCadastro.getText());
              enviarSV.writeUTF("atualizatxt");
              enviarSV.writeUTF("vamo");
              
              
               ci.show();
               ci.voltar();
                this.setVisible(false);
              }
              else{
                  JOptionPane.showMessageDialog(null, "Algum campo não preenchido");
              }
              
       
        } catch (IOException ex) {
            Logger.getLogger(Cadastrar.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Cadastrar.class.getName()).log(Level.SEVERE, null, ex);
        }
         
         
    }//GEN-LAST:event_OKCadastrarActionPerformed

   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelarCadastro;
    private javax.swing.JTextField LoginCadastro;
    private javax.swing.JButton OKCadastrar;
    private javax.swing.JTextField SenhaCadastro;
    private javax.swing.JTextField emailCadastro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
